#!/bin/bash

echo "🔄 Cyclic Deployment Guide"
echo "=========================="
echo ""
echo "Cyclic is super simple - no CLI needed!"
echo ""
echo "Steps:"
echo ""
echo "1. Go to https://app.cyclic.sh"
echo "2. Sign in with GitHub"
echo "3. Click 'Deploy' button"
echo "4. Select this repository"
echo "5. Click 'Connect'"
echo ""
echo "6. Add environment variables:"
echo "   - Click on your app"
echo "   - Go to 'Variables' tab"
echo "   - Add these variables:"
echo ""
echo "   NODE_ENV=production"
echo "   GROQ_API_KEY=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"
echo "   OPENROUTER_API_KEY=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"
echo "   GEMINI_API_KEY=AIzaSyC7zwRWScFvl9ZvhF2AsO7VFliNc2Sr3ok"
echo ""
echo "7. Cyclic will redeploy automatically"
echo "8. Copy your URL from the dashboard"
echo "   (looks like: https://parcimic-api.cyclic.app)"
echo ""
echo "9. Update frontend:"
echo "   ./deploy-frontend.sh https://your-app.cyclic.app"
echo ""
echo "✅ No credit card required!"
echo "✅ 10,000 requests per day on free tier"
echo ""
echo "That's it! 🎉"
