#!/bin/bash

echo "🚂 Railway Deployment Guide"
echo "============================"
echo ""
echo "Railway is one of the easiest platforms to deploy to!"
echo ""
echo "Steps:"
echo ""
echo "1. Go to https://railway.app"
echo "2. Click 'Start a New Project'"
echo "3. Select 'Deploy from GitHub repo'"
echo "4. Choose this repository"
echo "5. Railway will auto-detect Node.js and deploy"
echo ""
echo "6. Add environment variables:"
echo "   - Click on your service"
echo "   - Go to 'Variables' tab"
echo "   - Click 'Add Variable' and add these:"
echo ""
echo "   NODE_ENV=production"
echo "   GROQ_API_KEY=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"
echo "   OPENROUTER_API_KEY=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"
echo "   GEMINI_API_KEY=AIzaSyC7zwRWScFvl9ZvhF2AsO7VFliNc2Sr3ok"
echo ""
echo "7. Railway will redeploy automatically"
echo "8. Copy your URL from the 'Settings' tab"
echo "   (looks like: https://parcimic-api.up.railway.app)"
echo ""
echo "9. Update frontend:"
echo "   ./deploy-frontend.sh https://your-railway-url.up.railway.app"
echo ""
echo "That's it! 🎉"
