services:
  - type: web
    name: parcimic-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: OPENROUTER_MODEL
        value: google/gemma-3-12b-it:free
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: HF_MODEL
        value: HuggingFaceH4/zephyr-7b-beta
      - key: DEBUG
        value: false
